sudo: false
dist: trusty
language: node_js
node_js:
- '7'
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: jEAyS3cQ5GDa5sBF94EVNbPeTd9pFJMyavHHscSPuNUpQZhlRoXEEzhd6OKHolLcZ2qStE+aLAqtGa3pwvza8T35aol5Zj+dQfZzqtTlFR4M0rlEBZAFLTUM4T3sBtcGZ5kF/XKx75gMCzTZC4/E5qaJmF1++Iioj4JoPbOS69ONWnzqqyo1wRwQraiPkd+p/gZxsJn0H7MrZ4ISGgHlBRhHMYos3tGwNc+GLQWW1imIZOWkRKXCNwCHeJtHeBCmr2hjm0w7cweWfJEsLfAAPrGt5cSndY6XvRzZzpLFv+/O08N8IzUsi89jUuOkNysrOf1PcFPPIQPqTbyCrNSxhOfe9ta/1dapbUlhk/HQCE4Xh5Q+JW+rpXjnP6OM76tAfweskMwg7RTzh4eD7/tB7zutBGW3I/iRM2OLzCtArgZAcDyIMhBKfnqKH4axQnUECVbzu/mR1rAt3sKvCYfeqndEnjGP/ABOKD+b0w1OOxaRrjCZ+BW4ZuS/8Xg5TDjmXc8Sqe/z948siKnuJQhGAQBY0DokWxjhexeM5S/OuyRCl9uMRitml9WmApLCVR5XV1pYvDJBdsyqf6Rvv28cvZtNaT9ER99Yhe0xv6MzqSieK86YL34JBNlEB2DaBTtr70a5Y6FDfOYzDrbI50vEoIwrepgkXWeNoaXww/QuwCY=
  app: murmuring-brushlands-61068
